name: "Terraform Apply"

on:
    push:
        branches: ["main"]
    pull_request:

permissions:
    contents: read

env:
    ARM_CLIENT_ID: ${{secrets.AZURE_CLIENT_ID}}
    ARM_CLIENT_SECRET: ${{secrets.AZURE_CLIENT_SECRET}}
    ARM_SUBSCRIPTION_ID: ${{secrets.AZURE_SUBSCRIPTION_ID}}
    ARM_TENANT_ID: ${{secrets.AZURE_TENANT_ID}}

jobs:
    terraform-plan:
        name: "Terraform planing"
        runs-on: ubuntu-latest

        steps:
            # Checkout the repository to the GitHub Actions runner
            - name: Checkout
              uses: actions/checkout@v4

            # ** Login to Azure
            - name: Azure login
              uses: azure/login@v2
              with:
                  creds: ${{ secrets.AZURE_CREDENTIALS }}

            # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v3

            - name: Terraform init
              run: terraform init

            # ** Make Plan
            - name: Terraform Plan
              #  С тази команда запазване планът външно,и после ще го подадем на aply-я
              run: terraform plan -var-file=values.tfvars -out=terraform.plan

            - name: Upload Terraform Plan
              uses: actions/upload-artifact@v3
              with:
                  name: terraform-plan
                  path: terraform.plan
    terraform-apply:
        name: "Terraform Aply"
        runs-on: ubuntu-latest
        needs: terraform-plan

        steps:
            # Checkout the repository to the GitHub Actions runner
            - name: Checkout
              uses: actions/checkout@v4

            - name: Azure login
              uses: azure/login@v2
              with:
                  creds: ${{ secrets.AZURE_CREDENTIALS }}

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v3

            - name: Terraform init
              run: terraform init

            - name: Download terraform plan
              uses: actions/download-artifact@v3
              with:
                  name: terraform-plan
                  path: .

            - name: Terraform Applying
              run: terraform apply -auto-approve terraform.plan
